### ISSUE TITLE
ignore Sublime files

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/sib-dataportal#149]
Please ignore commiting and deploying Sublime files like "dataportal.sublime-project"

**Comment by danipilze** [comment]
actually i think it was commited by @ccubillos

**Comment by danipilze** [comment]
is this done? @ccubillos @mcubillos

**Comment by mcubillos** [comment]
Fixed in 4865402b6d9bcd5aee5bada0c1be78c3d7c3240e
