### ISSUE TITLE
Wrong publishers count 

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/sib-dataportal#151]
Publishers count says 23 but actually there are 42

![captura de pantalla 2015-02-05 a las 9 38 54 a m](https://cloud.githubusercontent.com/assets/3705866/6062068/d90ae81c-ad1a-11e4-8cd7-cb8c58cf7655.png)

**Comment by mcubillos** [comment]
This count is correct, the problem is that in the table data_provider the field gbif_approver need to be 'Colombia' to be taken into account in the previous count.
