### ISSUE TITLE
Remove taxonomic download

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/sib-dataportal#157]
Please remove both options for downloading species and taxonomic
it's not working and no worth to fix it using the new download system
http://data.sibcolombia.net/datasets/resource/245/

![seleccion_058](https://cloud.githubusercontent.com/assets/3705866/8850833/ea9caa1e-3110-11e5-8970-62a5d7115612.png)

**Comment by mcubillos** [comment]
Removed in 1ba34d7b97c662d5f7753d9a29fa39bfb0425ef4
