### ISSUE TITLE
Publisher link doesn't work

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/sib-dataportal#160]
in http://data.sibcolombia.net/datasets/resource/53/
the publisher link doesn't work

![seleccion_080](https://cloud.githubusercontent.com/assets/3705866/11006569/726fc668-8492-11e5-99f2-9c403ff1d355.png)

it sends to http://data.sibcolombia.net/datasets/provider/14
but this one actually works http://data.sibcolombia.net/publicadores/provider/14

**Comment by mcubillos** [comment]
Fixed in 247d79001cbce3daec1cc849c48c8a396dea1386
